/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.clinica_veterinaria;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
/**
 *
 * @author bra03
 */
public class Veterinario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Veterinario
     */
    public Veterinario() {
        initComponents();
        aplicarEstilo();
        aplicarFiltros();
        cargarDatos();
        // Populate fields when a row is clicked
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int fila = jTable1.getSelectedRow();
                if (fila >= 0) {
                    txtLicencia.setText(obj2str(jTable1.getValueAt(fila, 1)));
                    txtNombre.setText(obj2str(jTable1.getValueAt(fila, 2)));
                    txtApellido.setText(obj2str(jTable1.getValueAt(fila, 3)));
                    txtCorreo.setText(obj2str(jTable1.getValueAt(fila, 4)));
                    txtDui.setText(obj2str(jTable1.getValueAt(fila, 5)));
                    txtTelefono.setText(obj2str(jTable1.getValueAt(fila, 6)));
                    txtEspecialidad.setText(obj2str(jTable1.getValueAt(fila, 7)));
                }
            }
        });
    }
    private void aplicarFiltros() {
        Utilidades.soloLetras(txtNombre);
        Utilidades.soloLetras(txtApellido);
    }

    private void aplicarEstilo() {
        EstiloUI.aplicarVentana(getContentPane(), null,
            new javax.swing.JTable[]{jTable1},
            new javax.swing.JButton[]{btnGuardar, btnEditar, btnEliminar});
    }

    private String obj2str(Object o) { return o != null ? o.toString() : ""; }
    private void cargarDatos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Licencia");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Correo");
        modelo.addColumn("DUI");
        modelo.addColumn("Teléfono");
        modelo.addColumn("Especialidad");
        
        // Usamos tu variable jTable1
        jTable1.setModel(modelo);
        
        String sql = "SELECT id_veterinario, numero_licencia, nombre, apellido, correo, dui, telefono, especialidad FROM VETERINARIO";
        
        try {
            Connection con = Conexion.getConnection(); 
            if (con != null) {
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                while (rs.next()) {
                    Object[] fila = new Object[8];
                    fila[0] = rs.getInt("id_veterinario");
                    fila[1] = rs.getString("numero_licencia");
                    fila[2] = rs.getString("nombre");
                    fila[3] = rs.getString("apellido");
                    fila[4] = rs.getString("correo");
                    fila[5] = rs.getString("dui");
                    fila[6] = rs.getString("telefono");
                    fila[7] = rs.getString("especialidad");
                    modelo.addRow(fila);
                }
                con.close(); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar los datos: " + e.getMessage(), 
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtLicencia = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDui = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnEditar.setBackground(new java.awt.Color(50, 150, 50));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        btnGuardar.setBackground(new java.awt.Color(30, 100, 160));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(180, 40, 40));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        txtLicencia.setColumns(10);
        txtLicencia.addActionListener(this::txtLicenciaActionPerformed);

        txtNombre.setColumns(10);

        txtApellido.setColumns(10);

        txtCorreo.setColumns(10);

        txtDui.setColumns(10);

        txtTelefono.setColumns(10);

        txtEspecialidad.setColumns(10);

        jLabel1.setText("Licencias");

        jLabel2.setText("Apellido");

        jLabel3.setText("Correo");

        jLabel4.setText("Nombre");

        jLabel5.setText("Dui");

        jLabel6.setText("Especialidad");

        jLabel7.setText("Telefono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(329, 329, 329)
                        .addComponent(btnEditar)
                        .addGap(360, 360, 360)
                        .addComponent(btnEliminar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(37, 37, 37)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(45, 45, 45)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEspecialidad)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnEditar)))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = jTable1.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un veterinario de la tabla primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Obtenemos el ID de la columna 0
    int idVeterinario = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());
    
    // Confirmación
    int respuesta = JOptionPane.showConfirmDialog(this, "¿Seguro que querés eliminar este veterinario?", "Confirmar", JOptionPane.YES_NO_OPTION);
    
    if (respuesta == JOptionPane.YES_OPTION) {
        try {
            Connection con = Conexion.getConnection();
            String sql = "DELETE FROM VETERINARIO WHERE id_veterinario = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, idVeterinario);
            ps.executeUpdate();
            con.close();
            
            JOptionPane.showMessageDialog(this, "Veterinario eliminado con éxito.");
            cargarDatos(); // Recargamos la tabla
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar (Revisá que no tenga citas asignadas): " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String licencia    = txtLicencia.getText().trim();
        String nombre      = txtNombre.getText().trim();
        String apellido    = txtApellido.getText().trim();
        String correo      = txtCorreo.getText().trim();
        String dui         = txtDui.getText().trim();
        String telefono    = txtTelefono.getText().trim();
        String especialidad = txtEspecialidad.getText().trim();

        if (Utilidades.campoVacio(licencia)) {
            Utilidades.mostrarError(this, "El número de licencia es obligatorio."); return;
        }
        if (Utilidades.campoVacio(nombre)) {
            Utilidades.mostrarError(this, "El nombre es obligatorio."); return;
        }
        if (!Utilidades.validarSoloLetras(nombre)) {
            Utilidades.mostrarError(this, "El nombre solo puede contener letras."); return;
        }
        if (Utilidades.campoVacio(apellido)) {
            Utilidades.mostrarError(this, "El apellido es obligatorio."); return;
        }
        if (!Utilidades.validarSoloLetras(apellido)) {
            Utilidades.mostrarError(this, "El apellido solo puede contener letras."); return;
        }
        if (!dui.isEmpty() && !Utilidades.validarDUI(dui)) {
            Utilidades.mostrarError(this, "DUI inválido. Formato: 00000000-0"); return;
        }
        if (!correo.isEmpty() && !Utilidades.validarEmail(correo)) {
            Utilidades.mostrarError(this, "Correo electrónico inválido."); return;
        }
        if (!telefono.isEmpty() && !Utilidades.validarTelefono(telefono)) {
            Utilidades.mostrarError(this, "Teléfono inválido (7-15 dígitos)."); return;
        }

        String sql = "INSERT INTO VETERINARIO (id_usuario, numero_licencia, nombre, apellido, correo, dui, telefono, especialidad) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            Connection con = Conexion.getConnection();
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, Main.currentUserId);
            ps.setString(2, licencia);
            ps.setString(3, nombre);
            ps.setString(4, apellido);
            ps.setString(5, correo.isEmpty() ? null : correo);
            ps.setString(6, dui.isEmpty() ? null : dui);
            ps.setString(7, telefono.isEmpty() ? null : telefono);
            ps.setString(8, especialidad.isEmpty() ? null : especialidad);
            ps.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(this, "Veterinario guardado exitosamente.");
            cargarDatos();
            txtLicencia.setText(""); txtNombre.setText(""); txtApellido.setText("");
            txtCorreo.setText(""); txtDui.setText(""); txtTelefono.setText(""); txtEspecialidad.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int filaSeleccionada = jTable1.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un veterinario de la tabla para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idVeterinario = Integer.parseInt(jTable1.getValueAt(filaSeleccionada, 0).toString());

        String licencia     = txtLicencia.getText().trim();
        String nombre       = txtNombre.getText().trim();
        String apellido     = txtApellido.getText().trim();
        String correo       = txtCorreo.getText().trim();
        String dui          = txtDui.getText().trim();
        String telefono     = txtTelefono.getText().trim();
        String especialidad = txtEspecialidad.getText().trim();

        if (Utilidades.campoVacio(licencia)) {
            Utilidades.mostrarError(this, "El número de licencia es obligatorio."); return;
        }
        if (Utilidades.campoVacio(nombre)) {
            Utilidades.mostrarError(this, "El nombre es obligatorio."); return;
        }
        if (!Utilidades.validarSoloLetras(nombre)) {
            Utilidades.mostrarError(this, "El nombre solo puede contener letras."); return;
        }
        if (Utilidades.campoVacio(apellido)) {
            Utilidades.mostrarError(this, "El apellido es obligatorio."); return;
        }
        if (!Utilidades.validarSoloLetras(apellido)) {
            Utilidades.mostrarError(this, "El apellido solo puede contener letras."); return;
        }
        if (!dui.isEmpty() && !Utilidades.validarDUI(dui)) {
            Utilidades.mostrarError(this, "DUI inválido. Formato: 00000000-0"); return;
        }
        if (!correo.isEmpty() && !Utilidades.validarEmail(correo)) {
            Utilidades.mostrarError(this, "Correo electrónico inválido."); return;
        }
        if (!telefono.isEmpty() && !Utilidades.validarTelefono(telefono)) {
            Utilidades.mostrarError(this, "Teléfono inválido (7-15 dígitos)."); return;
        }

        try {
            Connection con = Conexion.getConnection();
            PreparedStatement ps = con.prepareStatement(
                "UPDATE VETERINARIO SET numero_licencia=?, nombre=?, apellido=?, correo=?, dui=?, telefono=?, especialidad=? WHERE id_veterinario=?");
            ps.setString(1, licencia);
            ps.setString(2, nombre);
            ps.setString(3, apellido);
            ps.setString(4, correo.isEmpty() ? null : correo);
            ps.setString(5, dui.isEmpty() ? null : dui);
            ps.setString(6, telefono.isEmpty() ? null : telefono);
            ps.setString(7, especialidad.isEmpty() ? null : especialidad);
            ps.setInt(8, idVeterinario);
            ps.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(this, "Veterinario actualizado exitosamente.");
            cargarDatos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al editar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDui;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
